version: '3.8'

services:
  demon_dice_app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./build/dockerfiles/app/Dockerfile
    depends_on:
      - demon_dice_db
    ports:
      - "${APP_PORT}:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
  demon_dice_db:
    container_name: ${DB_HOST}
    image: postgres:16.2
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${DB_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    
  pgadmin4:
    image: dpage/pgadmin4:8.4
    ports: 
    - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      # PassFileも一緒に配置したかったが、下記を参考にしてもうまくいかなかった
      # https://stackoverflow.com/questions/66578506/where-is-the-pgpass-file-in-pgadmin4-docker-container-when-this-file-is-mounted
      - ./config/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    depends_on:
      - demon_dice_db

volumes:
  db_data:
  pgadmin-data: